name: Trigger Oil Price Monitor

on:
  schedule:
      - cron: '30 4-14 * * 1-5'
        workflow_dispatch:

        jobs:
          trigger:
              runs-on: ubuntu-latest
                  steps:
                        - name: Trigger crude oil monitor workflow
                                run: curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TRIGGER_TOKEN }}" https://api.github.com/repos/NF-laidback/crude_price_monitor/dispatches -d '{"event_type":"check-oil-price"}'
